name: macos-latest

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-clang:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - run: cmake --workflow ci-clang
