name: ubuntu-latest

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-clang:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          sudo apt-get update
          sudo apt-get install -y build-essential clang
      - run: cmake --workflow ci-clang

  build-gcc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          sudo apt-get update
          sudo apt-get install -y build-essential
      - run: cmake --workflow ci-gcc
