name: windows-latest

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-msvc:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64
      - run: cmake --workflow ci-msvc
  build-clang:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: egor-tensin/setup-clang@v1
        with:
          platform: x64
      - run: cmake --workflow ci-clang
  build-mingw:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - run: cmake --workflow ci-gcc
