name: windows-latest

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-msvc:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Install file-cpp
        run: |
          git clone https://github.com/weqeqq/file-cpp.git
          cd file-cpp
          cmake --preset release -DFILE_BUILD_TESTS=OFF -DCMAKE_PREFIX_PATH=${{ github.workspace }}/prefix
          cmake --build --preset release --target install

      - name: Configure
        run: cmake --preset release -DPSD_BUILD_TESTS=ON -DCMAKE_PREFIX_PATH=${{ github.workspace }}/prefix

      - name: Build
        run: cmake --build --preset release

      - name: Test
        run: ctest --preset release

  build-clang:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Clang
        uses: egor-tensin/setup-clang@v1
        with:
          platform: x64

      - name: Install file-cpp
        run: |
          git clone https://github.com/weqeqq/file-cpp.git
          cd file-cpp
          cmake --preset release -DFILE_BUILD_TESTS=OFF -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -G Ninja -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/prefix
          cmake --build --preset release --target install

      - name: Configure
        run: cmake --preset release -DPSD_BUILD_TESTS=ON -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -G Ninja -DCMAKE_PREFIX_PATH=${{ github.workspace }}/prefix

      - name: Build
        run: cmake --build --preset release

      - name: Test
        run: ctest --preset release

  build-mingw:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install file-cpp
        run: |
          git clone https://github.com/weqeqq/file-cpp.git
          cd file-cpp
          cmake --preset release -DFILE_BUILD_TESTS=OFF -G "MinGW Makefiles" -DCMAKE_PREFIX_PATH=${{ github.workspace }}/prefix
          cmake --build --preset release --target install

      - name: Configure
        run: cmake --preset release -DPSD_BUILD_TESTS=ON -G "MinGW Makefiles" -DCMAKE_PREFIX_PATH=${{ github.workspace }}/prefix

      - name: Build
        run: cmake --build --preset release

      - name: Test
        run: ctest --preset release
